title: 김하연의 포트폴리오
name: 김하연
email: chocokakao@naver.com
description: >-

baseurl: ''
url: 'https://hayeonkimm.github.io'

# profile 이미지
profile_image: images/about.jpeg

# SNS 아이디
github_id: hayeonkimm
instagram_id: hayeonkimm

# Youtube vid
youtube_vid: #

# Custom Color
primary: 2c98f0 #b72cf0
primary_hover: ec5453 #44A4F2 #9a2dc7
color_1: 2c98f0 #b72cf0
color_2: ec5453
color_3: f9bf3f
color_4: a84cb8
color_5: 2fa499
color_6: 2fa499

# slider type 0  (텍스트가 우측 정렬된 슬라이더)
slider_0: # 형식에 맞추어 항목 추가
  - background_url: images/cover_bg_4.jpg
    title: <br>HayeonKIM</br>
    #   subtitle: >-
    #     hi<br>
    #     im<br>
    #     hayeon<br>
    #     and U?
    position: absolute
    transform: translate( -50%, -50%)
    left: 50px
    bottom: 50px

# - background_url: images/cover_bg_3.jpeg
#   title: Hi. <br>How R U?</br>
#   subtitle:
#   position : absolute
#   transform : translate( -50%, -50%)
#   left: 80px
#   bottom: 0px

# slider_0_color : rgb(255,255,255)

# slider type 1  (텍스트가 좌측 정렬된 슬라이더)
slider_1: # 형식에 맞추어 항목 추가
  - background_url: images/img_bg_3_.jpeg
    title: Hi. <br>HayeonKIM</br>
    subtitle:
    position: absolute
    transform: translate( -50%, -50%)
    left: 600px
    bottom: 400px

    slider_0_color: rgb(255,255,255)

# About
about_meta: About Me
about_header: >-
  "무엇이든 오래 고민하던 대학생"
about_introduce: >-
  "안녕하세요 늘 도전하는 김하연입니다 ."
about_content: >-
  <strong></strong>
about_services: # 형식에 맞추어 항목 추가
  - icon: icon-data
    name: Server
  - icon: icon-monitor
    name: Web
  # - icon: icon-phone3
  #   name: App
  - icon: icon-code
    name: Data Analysis
about_box_content: >-

  안될 거라는 말을 듣기보다,<br><br>해낼 수 있다라고 믿는 사람입니다.<br><br>

about_box_button:
  link: #
  name: >-
    You Can Do IT

# Tech  skill
tech_meta: TECH SKILLS
tech_header: 저는 현재 이것을 할 수 있습니다.
# tech_content: markdown으로 할수 있으면 좋을듯
tech_list: # 형식에 맞추어 항목 추가
  - name: Node.js
    color: color-5
    animation: fadeInLeft
    percent: 40
    mark: 40 # 이게 바를 조정한다.
    content: 스파르타코딩클럽-항해99 라는 부트캠프에서 Node.js를 주특기로 99일동안 숙련하였습니다. 현재 알고리즘 및 다양한 기술을 접목하여 더욱 깊게 공부 중입니다.

  - name: Python
    color: color-1
    animation: fadeInLeft
    percent: 30
    mark: 30 # 이게 바를 조정한다.
    content: 파이썬 기초, 데이터 분석과 시각화를 공부하고 파이썬 언어의 기본적인 문법에 대해 알고 있으며, 자료구조 및 알고리즘을 파이썬으로 공부하였습니다.

  - name: Github
    color: color-4
    animation: fadeInRight
    percent: 25
    mark: 25
    content: 대부분의 프로젝트를 github를 통해 소스 코드를 관리하였으며, 협업 역시 github을 통해 진행하였습니다. 또한 github서버를 활용하여 블로그 및 포트폴리오 사이트를 관리합니다.
#tech_desc:
# Project
project_meta: My Work
project_header: PROJECT

# project_my_name: 개인 프로젝트

project_my_name: 웹 프로젝트
project_my: # 형식에 맞추어 항목 추가
  - background_url: pdf/team.png
    animation: fadeInRight
    name: 항해99 - TeamNote
    description: 스파르타코딩클럽에서 주최하는 부트캠프 항해99에서 마지막으로 진행된 실전 프로젝트. 약 6주간 진행되었다.
    detail_url: pdf/발표자료.pdf
    readmore_url: https://github.com/The-HangHae99-final/the-Final-TeamNote.git

  - background_url: pdf/wanted.jpeg
    animation: fadeInRight
    name: 항해99 - 원티드
    description: 스파르타코딩클럽에서 주최하는 부트캠프 항해99에서 진행된 웹서비스 클론 프로젝트. 채용사이트 원티드를 타겟으로 두고 작업하였다. 약 1주간 진행되었다.
    detail_url:
    readmore_url: https://github.com/HayeonKimm/backend-ClonePro

  - background_url: pdf/mountain.png
    animation: fadeInRight
    name: 항해99 - Mountain Go
    description: 스파르타코딩클럽에서 주최하는 부트캠프 항해99에서 진행된 첫 풀스택 미니 프로젝트.
    detail_url:
    readmore_url: https://github.com/HayeonKimm/Mountain-Go.git

project_team_name: 데이터분석 프로젝트
project_team: # 형식에 맞추어 항목 추가
  - background_url: images/covid.png
    animation: fadeInRight
    name: XGBoost를 활용한 코로나19 예측
    description:2020 홍익대학교 도시공학과 졸업논문을 목적으로 시작된 프로젝트이다. 당시 코로나 19 확산세가 처음 시작된 이후 약 1달이 지난 상황이였고, 사태의 심각성을 인지하고 앞으로의 코로나 확산세를 예측하는 것을 목표로 두었다.
    detail_url: pdf/covid.pdf
    readmore_url: pdf/annae.pdf

  # project_team_name: 팀프로젝트
  # project_team: # 형식에 맞추어 항목 추가
  - background_url: images/jeju.png
    animation: fadeInRight
    name: 제주도 관광객 소비 패턴 분석 프로젝트
    description: 삼성 멀티캠퍼스에서 진행한 첫번째 분석 프로젝트. Python의 Pandas, numpy 등의 정형데이터 계산 라이브러리 주로 활용하였고, matplotlib, seaborn, Folium 등의 시각화 라이브러리를 활용하였다.
    detail_url: pdf/jeju.pdf
    readmore_url: https://github.com/HayeonKimm/Tourist_Consumption_Analysis

  - background_url: images/bus.png
    animation: fadeInRight
    name: 머신러닝을 활용한 버스도착시간 예측 모델
    description: 삼성 멀티캠퍼스에서 진행한 두번째 분석 프로젝트. 머신러닝을 활용한 첫번째 프로젝트였다. 실시간 데이터를 수집하여, 특정한 노선의 정거장 간의 버스도착시간을 예측하는 프로젝트였다. 사용한 스택은 python, spark, ubuntu 등이 있다.
    detail_url: pdf/bus.pdf
    readmore_url: https://github.com/HayeonKimm/bus-time-prediction

  - background_url: images/traffic.png
    animation: fadeInRight
    name: 교통 데이터를 활용한 웹서비스 프로젝트
    description: 삼성 멀티캠퍼스에서 진행한 파이널 프로젝트. 머신러닝을 활용한 웹 서비스 배포가 목적이였다. 크롤링한 교통 사고 데이터를 다각적으로 EDA 분석하고, 교통량 예측을 머신러닝으로 진행하였다. 
    detail_url: pdf/traffic.pdf
    readmore_url: https://github.com/HayeonKimm/Traffic-Webservice-1

# project_business_name: Business
# project_business: # 형식에 맞추어 항목 추가
# - background_url:
#   animation: fadeInTop
#   name:
#   description: >-

#   detail_url: #
#   readmore_url: #

# Experience
exp_meta: What have I achieved?
exp_header: 저는 이런 "경험"들을 해봤습니다.
exp_content: 회사에서 필요로 한다면 이런 역량도 가지고 있습니다.
exp_services: # 형식에 맞추어 항목 추가
  - name: 아이디어
    color: color-1
    icon: icon-bulb
    content: INTP의 특징인 아이디어 뱅크 특성을 가졌습니다. 팀원들의 브레인 스토밍과 아이디어 디벨롭을 돕습니다.
  - name: 기술습득
    color: color-2
    icon: icon-home
    content: 제가 선택한 길, 항상 열정을 다해 공부하며 새로운 기술에 대해 즐거운 마음으로 배웁니다.
  - name: 프로젝트
    color: color-3
    icon: icon-phone3
    content: 다양한 프로젝트를 기획, 진행 해왔기에 업무에 대한 협력과 배분이 익숙합니다. 새로운 프로젝트에 도전적입니다.
exp_counters:
  - name: 개발 공부시작 (DAY)
    count: 470
    speed: 10000
  - name: project (NUMBER)
    count: 5.00
    speed: 10000

# Career
# carerr_meta: career
# career_header: Work Career
# career_list:
# - name: 과기전통부 산학과제
#   date: 2020.06~2020.11
#   content: PlenOPtic Video에서 객체 tracking 연구  <br> 중대형 공간용 초고해상도 비정형 플렌옵틱 동영상 저작/재생 플랫폼 기술 개발
#   color: color-1
#   icon: icon-pen2
#   animation: fadeInLeft
# - name: Voice Caddie 산학과제
#   date: 2021.05~2021.10
#   content: 현재 골프치는 사람의 Pose와 Multi-view를 연구하고 있습니다.
#   color: color-2
#   icon: icon-pen2
#   animation: fadeInRight
# Education
edu_meta: Education
edu_header: Education
edu_list:
  - title: HONGIK UNIVERSITY URBAN ENGINEERING AND PLANING BACHELOR
    subtitle: 홍익대학교 도시공학과 졸업
    date: 2015.02 - 2021.08
    content:
  - title: SAMSUNG MULTICAMPUS
    subtitle: 데이터 사이언스 & 엔지니어링
    date: 2021.05 - 2021.10
    content:
  - title: HangHae99
    subtitle: 백엔드 엔지니어 과정
    date: 2022.05 - 2022.8
    content: >-

#Contact
contact_meta: Get in Touch
contact_header: Contact
contact_list:
  # - title: 이메일
  #   icon: icon-globe-outline
  #   url: hayeon.data@gmail.com
  # - title:
  #   icon: icon-map
  # - title:
  #   icon: icon-phone
  - title: Github 링크
    icon: icon-layers2
    url: https://github.com/HayeonKimm

  - title: 블로그 링크
    icon: icon-layers2
    url: https://summerlaftel07.tistory.com/

contact_message: <em>연락해주셔서 감사합니다.</em> 24시간이내에 회신드리도록 하겠습니다. :)

optional_front_matter:
  remove_originals: true
